"""feature store

Revision ID: 0873bc51594c
Revises:
Create Date: 2023-06-20 08:36:16.156527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0873bc51594c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies_ranked",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_title", sa.String(length=255), nullable=False),
        sa.Column("vote_count", sa.Float(), nullable=False),
        sa.Column("vote_average", sa.Float(), nullable=False),
        sa.Column("weighted_average", sa.Float(), nullable=False),
        sa.Column("popularity", sa.Float(), nullable=False),
        sa.Column("overview", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_movies_ranked_id"), "movies_ranked", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movies_ranked_id"), table_name="movies_ranked")
    op.drop_table("movies_ranked")
    # ### end Alembic commands ###
